/*!
 * CareersTiger Jobs — © 2026 CareersTiger. All rights reserved.
 * Proprietary and confidential. Unauthorized copying or distribution is prohibited.
 *
 * Source registry — the companies whose LIVE openings CareersTiger collects.
 * Each entry: { name, provider, slug, sectors }
 *   provider : internal fetch adapter key
 *   slug     : the company's board identifier on that system
 *   sectors  : free-form tags for your own reference
 *
 * To add a company, map its public careers URL to a provider + slug and add one line.
 * Open the in-app Diagnostics panel to see which companies returned jobs and prune the rest.
 * Every apply link produced here lands on the company's OWN application page.
 */
window.COMPANIES = [
  /* ================= LEVER ================= */
  { name: 'LeadSquared',      provider: 'lever', slug: 'leadsquared',   sectors: ['saas'] },
  { name: 'BrowserStack',     provider: 'lever', slug: 'browserstack',  sectors: ['saas'] },
  { name: 'MindTickle',       provider: 'lever', slug: 'mindtickle',    sectors: ['saas'] },
  { name: 'Netcore Cloud',    provider: 'lever', slug: 'netcore',       sectors: ['saas'] },
  { name: 'Whatfix',          provider: 'lever', slug: 'whatfix',       sectors: ['saas'] },
  { name: 'Spinny',           provider: 'lever', slug: 'spinny',        sectors: ['auto'] },
  { name: 'Simplilearn',      provider: 'lever', slug: 'simplilearn',   sectors: ['edtech'] },
  { name: 'upGrad',           provider: 'lever', slug: 'upgrad',        sectors: ['edtech'] },
  { name: 'MoEngage',         provider: 'lever', slug: 'moengage',      sectors: ['saas'] },
  { name: 'CleverTap',        provider: 'lever', slug: 'clevertap',     sectors: ['saas'] },
  { name: 'Locus',            provider: 'lever', slug: 'locus',         sectors: ['saas'] },
  { name: 'Vymo',             provider: 'lever', slug: 'vymo',          sectors: ['saas'] },
  { name: 'Capillary',        provider: 'lever', slug: 'capillary',     sectors: ['saas'] },
  { name: 'Yellow.ai',        provider: 'lever', slug: 'yellowmessenger', sectors: ['saas'] },
  { name: 'Exotel',           provider: 'lever', slug: 'exotel',        sectors: ['saas'] },
  { name: 'Meesho',           provider: 'lever', slug: 'meesho',        sectors: ['ecommerce'] },
  { name: 'Groww',            provider: 'lever', slug: 'groww',         sectors: ['fintech'] },
  { name: 'PhonePe',          provider: 'lever', slug: 'phonepe',       sectors: ['fintech'] },
  { name: 'Dream11',          provider: 'lever', slug: 'dreamsports',   sectors: ['gaming'] },
  { name: 'Sprinklr',         provider: 'lever', slug: 'sprinklr',      sectors: ['saas'] },
  { name: 'Postman (L)',      provider: 'lever', slug: 'postman',       sectors: ['saas'] },
  { name: 'Uni Cards',        provider: 'lever', slug: 'uni',           sectors: ['fintech'] },
  { name: 'Slice',            provider: 'lever', slug: 'slice',         sectors: ['fintech'] },
  { name: 'Jupiter',          provider: 'lever', slug: 'jupiter',       sectors: ['fintech'] },
  { name: 'BharatPe',         provider: 'lever', slug: 'bharatpe',      sectors: ['fintech'] },
  { name: 'Rupeek',           provider: 'lever', slug: 'rupeek',        sectors: ['fintech'] },
  { name: 'Cars24',           provider: 'lever', slug: 'cars24',        sectors: ['auto'] },
  { name: 'Zolve',            provider: 'lever', slug: 'zolve',         sectors: ['fintech'] },
  { name: 'Plum',             provider: 'lever', slug: 'plumhq',        sectors: ['insurtech'] },
  { name: 'Nexus',            provider: 'lever', slug: 'nexusmutual',   sectors: ['saas'] },
  { name: 'Springworks',      provider: 'lever', slug: 'springworks',  sectors: ['saas'] },
  { name: 'Observe.ai',       provider: 'lever', slug: 'observe',       sectors: ['saas'] },
  { name: 'Fi Money',         provider: 'lever', slug: 'epifi',         sectors: ['fintech'] },
  { name: 'Toplyne',          provider: 'lever', slug: 'toplyne',       sectors: ['saas'] },
  { name: 'Hevo Data',        provider: 'lever', slug: 'hevodata',      sectors: ['saas'] },
  { name: 'Fandom',           provider: 'lever', slug: 'fandom',        sectors: ['media'] },
  { name: 'KrazyBee',         provider: 'lever', slug: 'kreditbee',     sectors: ['fintech'] },
  { name: 'Turing',           provider: 'lever', slug: 'turing',        sectors: ['saas'] },

  /* ================= GREENHOUSE ================= */
  { name: 'Postman',          provider: 'greenhouse', slug: 'postman',       sectors: ['saas'] },
  { name: 'Hasura',           provider: 'greenhouse', slug: 'hasura',        sectors: ['saas'] },
  { name: 'Innovaccer',       provider: 'greenhouse', slug: 'innovaccer',    sectors: ['health'] },
  { name: 'Gupshup',          provider: 'greenhouse', slug: 'gupshup',       sectors: ['saas'] },
  { name: 'Amplitude',        provider: 'greenhouse', slug: 'amplitude',     sectors: ['saas'] },
  { name: 'MongoDB',          provider: 'greenhouse', slug: 'mongodb',       sectors: ['saas'] },
  { name: 'Twilio',           provider: 'greenhouse', slug: 'twilio',        sectors: ['saas'] },
  { name: 'Zscaler',          provider: 'greenhouse', slug: 'zscaler',       sectors: ['security'] },
  { name: 'HackerRank',       provider: 'greenhouse', slug: 'hackerrank',    sectors: ['saas'] },
  { name: 'Coursera',         provider: 'greenhouse', slug: 'coursera',      sectors: ['edtech'] },
  { name: 'Databricks',       provider: 'greenhouse', slug: 'databricks',    sectors: ['saas'] },
  { name: 'Airbnb',           provider: 'greenhouse', slug: 'airbnb',        sectors: ['travel'] },
  { name: 'Dropbox',          provider: 'greenhouse', slug: 'dropbox',       sectors: ['saas'] },
  { name: 'DoorDash',         provider: 'greenhouse', slug: 'doordash',      sectors: ['ops'] },
  { name: 'Stripe',           provider: 'greenhouse', slug: 'stripe',        sectors: ['fintech'] },
  { name: 'GitLab',           provider: 'greenhouse', slug: 'gitlab',        sectors: ['saas'] },
  { name: 'Chargebee',        provider: 'greenhouse', slug: 'chargebee',     sectors: ['saas'] },
  { name: 'Razorpay',         provider: 'greenhouse', slug: 'razorpaysoftwareprivatelimited', sectors: ['fintech'] },
  { name: 'Cloudflare',       provider: 'greenhouse', slug: 'cloudflare',    sectors: ['saas'] },
  { name: 'Datadog',          provider: 'greenhouse', slug: 'datadog',       sectors: ['saas'] },
  { name: 'Okta',             provider: 'greenhouse', slug: 'okta',          sectors: ['saas'] },
  { name: 'Samsara',          provider: 'greenhouse', slug: 'samsara',       sectors: ['saas'] },
  { name: 'Nutanix',          provider: 'greenhouse', slug: 'nutanix',       sectors: ['saas'] },
  { name: 'Confluent',        provider: 'greenhouse', slug: 'confluent',     sectors: ['saas'] },
  { name: 'Snyk',             provider: 'greenhouse', slug: 'snyk',          sectors: ['security'] },
  { name: 'HubSpot',          provider: 'greenhouse', slug: 'hubspot',       sectors: ['saas'] },
  { name: 'Coinbase',         provider: 'greenhouse', slug: 'coinbase',      sectors: ['fintech'] },
  { name: 'Segment',          provider: 'greenhouse', slug: 'segment',       sectors: ['saas'] },
  { name: 'Airtable',         provider: 'greenhouse', slug: 'airtable',      sectors: ['saas'] },
  { name: 'Instacart',        provider: 'greenhouse', slug: 'instacart',     sectors: ['ops'] },
  { name: 'Affirm',           provider: 'greenhouse', slug: 'affirm',        sectors: ['fintech'] },
  { name: 'Grammarly',        provider: 'greenhouse', slug: 'grammarly',     sectors: ['saas'] },
  { name: 'Freshprints',      provider: 'greenhouse', slug: 'freshprints',   sectors: ['ecommerce'] },
  { name: 'GoTo',             provider: 'greenhouse', slug: 'gotogroup',     sectors: ['saas'] },
  { name: 'ZoomInfo',         provider: 'greenhouse', slug: 'zoominfo',      sectors: ['saas'] },
  { name: 'Wise',             provider: 'greenhouse', slug: 'transferwise',  sectors: ['fintech'] },
  { name: 'Udemy',            provider: 'greenhouse', slug: 'udemy',         sectors: ['edtech'] },
  { name: 'Rubrik',           provider: 'greenhouse', slug: 'rubrik',        sectors: ['saas'] },
  { name: 'Sprinklr (G)',     provider: 'greenhouse', slug: 'sprinklr',      sectors: ['saas'] },
  { name: 'Highspot',         provider: 'greenhouse', slug: 'highspot',      sectors: ['saas'] },
  { name: 'Chargebee (G)',    provider: 'greenhouse', slug: 'chargebeeinc',  sectors: ['saas'] },
  { name: 'Peloton',          provider: 'greenhouse', slug: 'peloton',       sectors: ['fitness'] },
  { name: 'Notion',           provider: 'greenhouse', slug: 'notion',        sectors: ['saas'] },
  { name: 'Gong',             provider: 'greenhouse', slug: 'gong',          sectors: ['saas'] },
  { name: 'Asana',            provider: 'greenhouse', slug: 'asana',         sectors: ['saas'] },
  { name: 'Postman GTM',      provider: 'greenhouse', slug: 'postmanlabs',   sectors: ['saas'] },

  /* ================= ASHBY ================= */
  { name: 'Atlan',            provider: 'ashby', slug: 'atlan',          sectors: ['saas'] },
  { name: 'Zluri',            provider: 'ashby', slug: 'zluri',          sectors: ['saas'] },
  { name: 'Sprinto',          provider: 'ashby', slug: 'sprinto',        sectors: ['saas'] },
  { name: 'Nextbillion.ai',   provider: 'ashby', slug: 'nextbillion',    sectors: ['saas'] },
  { name: 'Fountane',         provider: 'ashby', slug: 'fountane',       sectors: ['saas'] },
  { name: 'Rippling',         provider: 'ashby', slug: 'rippling',       sectors: ['saas'] },
  { name: 'Deel',             provider: 'ashby', slug: 'deel',           sectors: ['saas'] },
  { name: 'Ramp',             provider: 'ashby', slug: 'ramp',           sectors: ['fintech'] },
  { name: 'Runway',           provider: 'ashby', slug: 'runwayml',       sectors: ['ai'] },
  { name: 'Vercel',           provider: 'ashby', slug: 'vercel',         sectors: ['saas'] },
  { name: 'Linear',           provider: 'ashby', slug: 'linear',         sectors: ['saas'] },
  { name: 'Perplexity',       provider: 'ashby', slug: 'perplexity',     sectors: ['ai'] },
  { name: 'Cohere',           provider: 'ashby', slug: 'cohere',         sectors: ['ai'] },
  { name: 'Mistral',          provider: 'ashby', slug: 'mistral',        sectors: ['ai'] },
  { name: 'Zepto',            provider: 'ashby', slug: 'zepto',          sectors: ['ecommerce'] },
  { name: 'Darwinbox',        provider: 'ashby', slug: 'darwinbox',      sectors: ['saas'] },
  { name: 'Fyle',             provider: 'ashby', slug: 'fyle',           sectors: ['saas'] },
  { name: 'Kong',             provider: 'ashby', slug: 'konghq',         sectors: ['saas'] },
  { name: 'Weights & Biases', provider: 'ashby', slug: 'wandb',          sectors: ['ai'] },
  { name: 'Replit',           provider: 'ashby', slug: 'replit',         sectors: ['saas'] },
  { name: 'Ramp Ops',         provider: 'ashby', slug: 'ramp',           sectors: ['fintech'] },
  { name: 'Modern Treasury',  provider: 'ashby', slug: 'moderntreasury', sectors: ['fintech'] },
  { name: 'Clipboard Health',  provider: 'ashby', slug: 'clipboardhealth', sectors: ['health'] },
  { name: 'OpenPhone',        provider: 'ashby', slug: 'openphone',      sectors: ['saas'] },
  { name: 'Multiplier',       provider: 'ashby', slug: 'multiplier',     sectors: ['saas'] },
  { name: 'Fitmint',          provider: 'ashby', slug: 'fitmint',        sectors: ['fitness'] },

  /* ================= SMARTRECRUITERS ================= */
  { name: 'Publicis Sapient', provider: 'smartrecruiters', slug: 'PublicisSapient', sectors: ['it-services'] },
  { name: 'Bosch',            provider: 'smartrecruiters', slug: 'BoschGroup',      sectors: ['engineering'] },
  { name: 'Visa',             provider: 'smartrecruiters', slug: 'Visa',            sectors: ['fintech'] },
  { name: 'Ubisoft',          provider: 'smartrecruiters', slug: 'Ubisoft2',        sectors: ['gaming'] },
  { name: 'McDonalds',        provider: 'smartrecruiters', slug: 'McDonalds',       sectors: ['retail'] },
  { name: 'Alorica',          provider: 'smartrecruiters', slug: 'Alorica',         sectors: ['bpo'] },
  { name: 'Foundever',        provider: 'smartrecruiters', slug: 'Foundever',       sectors: ['bpo'] },
  { name: 'IKEA',             provider: 'smartrecruiters', slug: 'IKEA',            sectors: ['retail'] },
  { name: 'Avis Budget',      provider: 'smartrecruiters', slug: 'AvisBudgetGroup', sectors: ['travel'] },
  { name: 'Biocon',           provider: 'smartrecruiters', slug: 'Biocon',          sectors: ['pharma'] },
  { name: 'Marlink',          provider: 'smartrecruiters', slug: 'Marlink',         sectors: ['telecom'] },
  { name: 'Experian',         provider: 'smartrecruiters', slug: 'Experian',        sectors: ['fintech'] },
  { name: 'World Bank',       provider: 'smartrecruiters', slug: 'WorldBankGroup',  sectors: ['finance'] },
  { name: 'Signify',          provider: 'smartrecruiters', slug: 'Signify',         sectors: ['engineering'] },

  /* ================= RECRUITEE ================= */
  { name: 'Chargebee Ops',    provider: 'recruitee', slug: 'chargebee',     sectors: ['saas'] },
  { name: 'Toddle',           provider: 'recruitee', slug: 'toddle',        sectors: ['edtech'] },
  { name: 'Scalefusion',      provider: 'recruitee', slug: 'scalefusion',   sectors: ['saas'] },
  { name: 'Mindbowser',       provider: 'recruitee', slug: 'mindbowser',    sectors: ['it-services'] },
  { name: 'Peppermint',       provider: 'recruitee', slug: 'peppermint',    sectors: ['saas'] },
  { name: 'InVideo',          provider: 'recruitee', slug: 'invideo',       sectors: ['saas'] },

  /* ================= SMALL / MID INDIAN — edtech · KPO · fintech · consumer ================= */
  /* Workable (many Indian startups use it) */
  { name: 'Testbook',         provider: 'workable', slug: 'testbook',       sectors: ['edtech'] },
  { name: 'Classplus',        provider: 'workable', slug: 'classplus',      sectors: ['edtech'] },
  { name: 'Teachmint',        provider: 'workable', slug: 'teachmint',      sectors: ['edtech'] },
  { name: 'PhysicsWallah',    provider: 'workable', slug: 'physicswallah',  sectors: ['edtech'] },
  { name: 'Newton School',    provider: 'workable', slug: 'newtonschool',   sectors: ['edtech'] },
  { name: 'AdmitKard',        provider: 'workable', slug: 'admitkard',      sectors: ['edtech'] },
  { name: 'Leverage Edu',     provider: 'workable', slug: 'leverageedu',    sectors: ['edtech'] },
  { name: 'Jar',              provider: 'workable', slug: 'jar',            sectors: ['fintech'] },
  { name: 'FamPay',           provider: 'workable', slug: 'fampay',         sectors: ['fintech'] },
  { name: 'Refyne',           provider: 'workable', slug: 'refyne',         sectors: ['fintech'] },
  { name: 'Progcap',          provider: 'workable', slug: 'progcap',        sectors: ['fintech'] },
  { name: 'Khatabook',        provider: 'workable', slug: 'khatabook',      sectors: ['fintech'] },
  { name: 'Bijnis',           provider: 'workable', slug: 'bijnis',         sectors: ['ecommerce'] },
  { name: 'ShopKirana',       provider: 'workable', slug: 'shopkirana',     sectors: ['ecommerce'] },
  { name: 'Pepper Content',   provider: 'workable', slug: 'peppercontent',  sectors: ['content'] },
  { name: 'BharatAgri',       provider: 'workable', slug: 'bharatagri',     sectors: ['agri'] },
  { name: 'Vahan',            provider: 'workable', slug: 'vahan',          sectors: ['staffing'] },
  { name: 'GrowthSchool',     provider: 'workable', slug: 'growthschool',   sectors: ['edtech'] },

  /* Lever / Greenhouse / Ashby — Indian edtech, KPO/analytics, consumer */
  { name: 'Vedantu',          provider: 'lever', slug: 'vedantu',          sectors: ['edtech'] },
  { name: 'Great Learning',   provider: 'lever', slug: 'greatlearning',    sectors: ['edtech'] },
  { name: 'Scaler',           provider: 'lever', slug: 'scaler',           sectors: ['edtech'] },
  { name: 'Emeritus',         provider: 'lever', slug: 'emeritus',         sectors: ['edtech'] },
  { name: 'Eruditus',         provider: 'lever', slug: 'eruditus',         sectors: ['edtech'] },
  { name: 'Unacademy',        provider: 'lever', slug: 'unacademy',        sectors: ['edtech'] },
  { name: 'Cuemath',          provider: 'lever', slug: 'cuemath',          sectors: ['edtech'] },
  { name: 'Tiger Analytics',  provider: 'lever', slug: 'tigeranalytics',   sectors: ['kpo','analytics'] },
  { name: 'Fractal',          provider: 'greenhouse', slug: 'fractalanalytics', sectors: ['kpo','analytics'] },
  { name: 'Straive',          provider: 'smartrecruiters', slug: 'Straive', sectors: ['kpo'] },
  { name: 'MergerWare',       provider: 'recruitee', slug: 'mergerware',   sectors: ['kpo','saas'] },
  { name: 'Betterplace',      provider: 'lever', slug: 'betterplace',      sectors: ['staffing','bpo'] },
  { name: 'Awign',            provider: 'lever', slug: 'awign',            sectors: ['staffing','bpo'] },
  { name: 'MyOperator',       provider: 'workable', slug: 'myoperator',    sectors: ['saas','bpo'] },
  { name: 'Squadstack',       provider: 'lever', slug: 'squadstack',       sectors: ['bpo','sales'] },
  { name: 'Kapture CX',       provider: 'workable', slug: 'kapturecrm',    sectors: ['saas','bpo'] },
  { name: 'Ozonetel',         provider: 'workable', slug: 'ozonetel',      sectors: ['saas','bpo'] },
  { name: 'Verloop.io',       provider: 'workable', slug: 'verloop',       sectors: ['saas','bpo'] }
];
