/*!
 * CareersTiger Jobs — © 2026 CareersTiger. All rights reserved.
 * Proprietary and confidential. Unauthorized copying or distribution is prohibited.
 *
 * Source registry — the companies whose LIVE openings CareersTiger collects.
 * Each entry: { name, provider, slug, sectors }
 *   provider : internal fetch adapter key
 *   slug     : the company's board identifier on that system
 *   sectors  : free-form tags for your own reference
 *
 * To add a company, map its public careers URL to a provider + slug and add one line.
 * Open the in-app Diagnostics panel to see which companies returned jobs and prune the rest.
 * Every apply link produced here lands on the company's OWN application page.
 */
window.COMPANIES = [
  /* ================= LEVER ================= */
  { name: 'LeadSquared',      provider: 'lever', slug: 'leadsquared',   sectors: ['saas'] },
  { name: 'BrowserStack',     provider: 'lever', slug: 'browserstack',  sectors: ['saas'] },
  { name: 'MindTickle',       provider: 'lever', slug: 'mindtickle',    sectors: ['saas'] },
  { name: 'Netcore Cloud',    provider: 'lever', slug: 'netcore',       sectors: ['saas'] },
  { name: 'Whatfix',          provider: 'lever', slug: 'whatfix',       sectors: ['saas'] },
  { name: 'Spinny',           provider: 'lever', slug: 'spinny',        sectors: ['auto'] },
  { name: 'Simplilearn',      provider: 'lever', slug: 'simplilearn',   sectors: ['edtech'] },
  { name: 'upGrad',           provider: 'lever', slug: 'upgrad',        sectors: ['edtech'] },
  { name: 'MoEngage',         provider: 'lever', slug: 'moengage',      sectors: ['saas'] },
  { name: 'CleverTap',        provider: 'lever', slug: 'clevertap',     sectors: ['saas'] },
  { name: 'Locus',            provider: 'lever', slug: 'locus',         sectors: ['saas'] },
  { name: 'Vymo',             provider: 'lever', slug: 'vymo',          sectors: ['saas'] },
  { name: 'Capillary',        provider: 'lever', slug: 'capillary',     sectors: ['saas'] },
  { name: 'Yellow.ai',        provider: 'lever', slug: 'yellowmessenger', sectors: ['saas'] },
  { name: 'Exotel',           provider: 'lever', slug: 'exotel',        sectors: ['saas'] },
  { name: 'Meesho',           provider: 'lever', slug: 'meesho',        sectors: ['ecommerce'] },
  { name: 'Groww',            provider: 'lever', slug: 'groww',         sectors: ['fintech'] },
  { name: 'PhonePe',          provider: 'lever', slug: 'phonepe',       sectors: ['fintech'] },
  { name: 'Dream11',          provider: 'lever', slug: 'dreamsports',   sectors: ['gaming'] },
  { name: 'Sprinklr',         provider: 'lever', slug: 'sprinklr',      sectors: ['saas'] },
  { name: 'Postman (L)',      provider: 'lever', slug: 'postman',       sectors: ['saas'] },
  { name: 'Uni Cards',        provider: 'lever', slug: 'uni',           sectors: ['fintech'] },
  { name: 'Slice',            provider: 'lever', slug: 'slice',         sectors: ['fintech'] },
  { name: 'Jupiter',          provider: 'lever', slug: 'jupiter',       sectors: ['fintech'] },
  { name: 'BharatPe',         provider: 'lever', slug: 'bharatpe',      sectors: ['fintech'] },
  { name: 'Rupeek',           provider: 'lever', slug: 'rupeek',        sectors: ['fintech'] },
  { name: 'Cars24',           provider: 'lever', slug: 'cars24',        sectors: ['auto'] },
  { name: 'Zolve',            provider: 'lever', slug: 'zolve',         sectors: ['fintech'] },
  { name: 'Plum',             provider: 'lever', slug: 'plumhq',        sectors: ['insurtech'] },
  { name: 'Nexus',            provider: 'lever', slug: 'nexusmutual',   sectors: ['saas'] },
  { name: 'Springworks',      provider: 'lever', slug: 'springworks',  sectors: ['saas'] },
  { name: 'Observe.ai',       provider: 'lever', slug: 'observe',       sectors: ['saas'] },
  { name: 'Fi Money',         provider: 'lever', slug: 'epifi',         sectors: ['fintech'] },
  { name: 'Toplyne',          provider: 'lever', slug: 'toplyne',       sectors: ['saas'] },
  { name: 'Hevo Data',        provider: 'lever', slug: 'hevodata',      sectors: ['saas'] },
  { name: 'Fandom',           provider: 'lever', slug: 'fandom',        sectors: ['media'] },
  { name: 'KrazyBee',         provider: 'lever', slug: 'kreditbee',     sectors: ['fintech'] },
  { name: 'Turing',           provider: 'lever', slug: 'turing',        sectors: ['saas'] },

  /* ================= GREENHOUSE ================= */
  { name: 'Postman',          provider: 'greenhouse', slug: 'postman',       sectors: ['saas'] },
  { name: 'Hasura',           provider: 'greenhouse', slug: 'hasura',        sectors: ['saas'] },
  { name: 'Innovaccer',       provider: 'greenhouse', slug: 'innovaccer',    sectors: ['health'] },
  { name: 'Gupshup',          provider: 'greenhouse', slug: 'gupshup',       sectors: ['saas'] },
  { name: 'Amplitude',        provider: 'greenhouse', slug: 'amplitude',     sectors: ['saas'] },
  { name: 'MongoDB',          provider: 'greenhouse', slug: 'mongodb',       sectors: ['saas'] },
  { name: 'Twilio',           provider: 'greenhouse', slug: 'twilio',        sectors: ['saas'] },
  { name: 'Zscaler',          provider: 'greenhouse', slug: 'zscaler',       sectors: ['security'] },
  { name: 'HackerRank',       provider: 'greenhouse', slug: 'hackerrank',    sectors: ['saas'] },
  { name: 'Coursera',         provider: 'greenhouse', slug: 'coursera',      sectors: ['edtech'] },
  { name: 'Databricks',       provider: 'greenhouse', slug: 'databricks',    sectors: ['saas'] },
  { name: 'Airbnb',           provider: 'greenhouse', slug: 'airbnb',        sectors: ['travel'] },
  { name: 'Dropbox',          provider: 'greenhouse', slug: 'dropbox',       sectors: ['saas'] },
  { name: 'DoorDash',         provider: 'greenhouse', slug: 'doordash',      sectors: ['ops'] },
  { name: 'Stripe',           provider: 'greenhouse', slug: 'stripe',        sectors: ['fintech'] },
  { name: 'GitLab',           provider: 'greenhouse', slug: 'gitlab',        sectors: ['saas'] },
  { name: 'Chargebee',        provider: 'greenhouse', slug: 'chargebee',     sectors: ['saas'] },
  { name: 'Razorpay',         provider: 'greenhouse', slug: 'razorpaysoftwareprivatelimited', sectors: ['fintech'] },
  { name: 'Cloudflare',       provider: 'greenhouse', slug: 'cloudflare',    sectors: ['saas'] },
  { name: 'Datadog',          provider: 'greenhouse', slug: 'datadog',       sectors: ['saas'] },
  { name: 'Okta',             provider: 'greenhouse', slug: 'okta',          sectors: ['saas'] },
  { name: 'Samsara',          provider: 'greenhouse', slug: 'samsara',       sectors: ['saas'] },
  { name: 'Nutanix',          provider: 'greenhouse', slug: 'nutanix',       sectors: ['saas'] },
  { name: 'Confluent',        provider: 'greenhouse', slug: 'confluent',     sectors: ['saas'] },
  { name: 'Snyk',             provider: 'greenhouse', slug: 'snyk',          sectors: ['security'] },
  { name: 'HubSpot',          provider: 'greenhouse', slug: 'hubspot',       sectors: ['saas'] },
  { name: 'Coinbase',         provider: 'greenhouse', slug: 'coinbase',      sectors: ['fintech'] },
  { name: 'Segment',          provider: 'greenhouse', slug: 'segment',       sectors: ['saas'] },
  { name: 'Airtable',         provider: 'greenhouse', slug: 'airtable',      sectors: ['saas'] },
  { name: 'Instacart',        provider: 'greenhouse', slug: 'instacart',     sectors: ['ops'] },
  { name: 'Affirm',           provider: 'greenhouse', slug: 'affirm',        sectors: ['fintech'] },
  { name: 'Grammarly',        provider: 'greenhouse', slug: 'grammarly',     sectors: ['saas'] },
  { name: 'Freshprints',      provider: 'greenhouse', slug: 'freshprints',   sectors: ['ecommerce'] },
  { name: 'GoTo',             provider: 'greenhouse', slug: 'gotogroup',     sectors: ['saas'] },
  { name: 'ZoomInfo',         provider: 'greenhouse', slug: 'zoominfo',      sectors: ['saas'] },
  { name: 'Wise',             provider: 'greenhouse', slug: 'transferwise',  sectors: ['fintech'] },
  { name: 'Udemy',            provider: 'greenhouse', slug: 'udemy',         sectors: ['edtech'] },
  { name: 'Rubrik',           provider: 'greenhouse', slug: 'rubrik',        sectors: ['saas'] },
  { name: 'Sprinklr (G)',     provider: 'greenhouse', slug: 'sprinklr',      sectors: ['saas'] },
  { name: 'Highspot',         provider: 'greenhouse', slug: 'highspot',      sectors: ['saas'] },
  { name: 'Chargebee (G)',    provider: 'greenhouse', slug: 'chargebeeinc',  sectors: ['saas'] },
  { name: 'Peloton',          provider: 'greenhouse', slug: 'peloton',       sectors: ['fitness'] },
  { name: 'Notion',           provider: 'greenhouse', slug: 'notion',        sectors: ['saas'] },
  { name: 'Gong',             provider: 'greenhouse', slug: 'gong',          sectors: ['saas'] },
  { name: 'Asana',            provider: 'greenhouse', slug: 'asana',         sectors: ['saas'] },
  { name: 'Postman GTM',      provider: 'greenhouse', slug: 'postmanlabs',   sectors: ['saas'] },

  /* ================= ASHBY ================= */
  { name: 'Atlan',            provider: 'ashby', slug: 'atlan',          sectors: ['saas'] },
  { name: 'Zluri',            provider: 'ashby', slug: 'zluri',          sectors: ['saas'] },
  { name: 'Sprinto',          provider: 'ashby', slug: 'sprinto',        sectors: ['saas'] },
  { name: 'Nextbillion.ai',   provider: 'ashby', slug: 'nextbillion',    sectors: ['saas'] },
  { name: 'Fountane',         provider: 'ashby', slug: 'fountane',       sectors: ['saas'] },
  { name: 'Rippling',         provider: 'ashby', slug: 'rippling',       sectors: ['saas'] },
  { name: 'Deel',             provider: 'ashby', slug: 'deel',           sectors: ['saas'] },
  { name: 'Ramp',             provider: 'ashby', slug: 'ramp',           sectors: ['fintech'] },
  { name: 'Runway',           provider: 'ashby', slug: 'runwayml',       sectors: ['ai'] },
  { name: 'Vercel',           provider: 'ashby', slug: 'vercel',         sectors: ['saas'] },
  { name: 'Linear',           provider: 'ashby', slug: 'linear',         sectors: ['saas'] },
  { name: 'Perplexity',       provider: 'ashby', slug: 'perplexity',     sectors: ['ai'] },
  { name: 'Cohere',           provider: 'ashby', slug: 'cohere',         sectors: ['ai'] },
  { name: 'Mistral',          provider: 'ashby', slug: 'mistral',        sectors: ['ai'] },
  { name: 'Zepto',            provider: 'ashby', slug: 'zepto',          sectors: ['ecommerce'] },
  { name: 'Darwinbox',        provider: 'ashby', slug: 'darwinbox',      sectors: ['saas'] },
  { name: 'Fyle',             provider: 'ashby', slug: 'fyle',           sectors: ['saas'] },
  { name: 'Kong',             provider: 'ashby', slug: 'konghq',         sectors: ['saas'] },
  { name: 'Weights & Biases', provider: 'ashby', slug: 'wandb',          sectors: ['ai'] },
  { name: 'Replit',           provider: 'ashby', slug: 'replit',         sectors: ['saas'] },
  { name: 'Ramp Ops',         provider: 'ashby', slug: 'ramp',           sectors: ['fintech'] },
  { name: 'Modern Treasury',  provider: 'ashby', slug: 'moderntreasury', sectors: ['fintech'] },
  { name: 'Clipboard Health',  provider: 'ashby', slug: 'clipboardhealth', sectors: ['health'] },
  { name: 'OpenPhone',        provider: 'ashby', slug: 'openphone',      sectors: ['saas'] },
  { name: 'Multiplier',       provider: 'ashby', slug: 'multiplier',     sectors: ['saas'] },
  { name: 'Fitmint',          provider: 'ashby', slug: 'fitmint',        sectors: ['fitness'] },

  /* ================= SMARTRECRUITERS ================= */
  { name: 'Publicis Sapient', provider: 'smartrecruiters', slug: 'PublicisSapient', sectors: ['it-services'] },
  { name: 'Bosch',            provider: 'smartrecruiters', slug: 'BoschGroup',      sectors: ['engineering'] },
  { name: 'Visa',             provider: 'smartrecruiters', slug: 'Visa',            sectors: ['fintech'] },
  { name: 'Ubisoft',          provider: 'smartrecruiters', slug: 'Ubisoft2',        sectors: ['gaming'] },
  { name: 'McDonalds',        provider: 'smartrecruiters', slug: 'McDonalds',       sectors: ['retail'] },
  { name: 'Alorica',          provider: 'smartrecruiters', slug: 'Alorica',         sectors: ['bpo'] },
  { name: 'Foundever',        provider: 'smartrecruiters', slug: 'Foundever',       sectors: ['bpo'] },
  { name: 'IKEA',             provider: 'smartrecruiters', slug: 'IKEA',            sectors: ['retail'] },
  { name: 'Avis Budget',      provider: 'smartrecruiters', slug: 'AvisBudgetGroup', sectors: ['travel'] },
  { name: 'Biocon',           provider: 'smartrecruiters', slug: 'Biocon',          sectors: ['pharma'] },
  { name: 'Marlink',          provider: 'smartrecruiters', slug: 'Marlink',         sectors: ['telecom'] },
  { name: 'Experian',         provider: 'smartrecruiters', slug: 'Experian',        sectors: ['fintech'] },
  { name: 'World Bank',       provider: 'smartrecruiters', slug: 'WorldBankGroup',  sectors: ['finance'] },
  { name: 'Signify',          provider: 'smartrecruiters', slug: 'Signify',         sectors: ['engineering'] },

  /* ================= RECRUITEE ================= */
  { name: 'Chargebee Ops',    provider: 'recruitee', slug: 'chargebee',     sectors: ['saas'] },
  { name: 'Toddle',           provider: 'recruitee', slug: 'toddle',        sectors: ['edtech'] },
  { name: 'Scalefusion',      provider: 'recruitee', slug: 'scalefusion',   sectors: ['saas'] },
  { name: 'Mindbowser',       provider: 'recruitee', slug: 'mindbowser',    sectors: ['it-services'] },
  { name: 'Peppermint',       provider: 'recruitee', slug: 'peppermint',    sectors: ['saas'] },
  { name: 'InVideo',          provider: 'recruitee', slug: 'invideo',       sectors: ['saas'] },

  /* ================= SMALL / MID INDIAN — edtech · KPO · fintech · consumer ================= */
  /* Workable (many Indian startups use it) */
  { name: 'Testbook',         provider: 'workable', slug: 'testbook',       sectors: ['edtech'] },
  { name: 'Classplus',        provider: 'workable', slug: 'classplus',      sectors: ['edtech'] },
  { name: 'Teachmint',        provider: 'workable', slug: 'teachmint',      sectors: ['edtech'] },
  { name: 'PhysicsWallah',    provider: 'workable', slug: 'physicswallah',  sectors: ['edtech'] },
  { name: 'Newton School',    provider: 'workable', slug: 'newtonschool',   sectors: ['edtech'] },
  { name: 'AdmitKard',        provider: 'workable', slug: 'admitkard',      sectors: ['edtech'] },
  { name: 'Leverage Edu',     provider: 'workable', slug: 'leverageedu',    sectors: ['edtech'] },
  { name: 'Jar',              provider: 'workable', slug: 'jar',            sectors: ['fintech'] },
  { name: 'FamPay',           provider: 'workable', slug: 'fampay',         sectors: ['fintech'] },
  { name: 'Refyne',           provider: 'workable', slug: 'refyne',         sectors: ['fintech'] },
  { name: 'Progcap',          provider: 'workable', slug: 'progcap',        sectors: ['fintech'] },
  { name: 'Khatabook',        provider: 'workable', slug: 'khatabook',      sectors: ['fintech'] },
  { name: 'Bijnis',           provider: 'workable', slug: 'bijnis',         sectors: ['ecommerce'] },
  { name: 'ShopKirana',       provider: 'workable', slug: 'shopkirana',     sectors: ['ecommerce'] },
  { name: 'Pepper Content',   provider: 'workable', slug: 'peppercontent',  sectors: ['content'] },
  { name: 'BharatAgri',       provider: 'workable', slug: 'bharatagri',     sectors: ['agri'] },
  { name: 'Vahan',            provider: 'workable', slug: 'vahan',          sectors: ['staffing'] },
  { name: 'GrowthSchool',     provider: 'workable', slug: 'growthschool',   sectors: ['edtech'] },

  /* Lever / Greenhouse / Ashby — Indian edtech, KPO/analytics, consumer */
  { name: 'Vedantu',          provider: 'lever', slug: 'vedantu',          sectors: ['edtech'] },
  { name: 'Great Learning',   provider: 'lever', slug: 'greatlearning',    sectors: ['edtech'] },
  { name: 'Scaler',           provider: 'lever', slug: 'scaler',           sectors: ['edtech'] },
  { name: 'Emeritus',         provider: 'lever', slug: 'emeritus',         sectors: ['edtech'] },
  { name: 'Eruditus',         provider: 'lever', slug: 'eruditus',         sectors: ['edtech'] },
  { name: 'Unacademy',        provider: 'lever', slug: 'unacademy',        sectors: ['edtech'] },
  { name: 'Cuemath',          provider: 'lever', slug: 'cuemath',          sectors: ['edtech'] },
  { name: 'Tiger Analytics',  provider: 'lever', slug: 'tigeranalytics',   sectors: ['kpo','analytics'] },
  { name: 'Fractal',          provider: 'greenhouse', slug: 'fractalanalytics', sectors: ['kpo','analytics'] },
  { name: 'Straive',          provider: 'smartrecruiters', slug: 'Straive', sectors: ['kpo'] },
  { name: 'MergerWare',       provider: 'recruitee', slug: 'mergerware',   sectors: ['kpo','saas'] },
  { name: 'Betterplace',      provider: 'lever', slug: 'betterplace',      sectors: ['staffing','bpo'] },
  { name: 'Awign',            provider: 'lever', slug: 'awign',            sectors: ['staffing','bpo'] },
  { name: 'MyOperator',       provider: 'workable', slug: 'myoperator',    sectors: ['saas','bpo'] },
  { name: 'Squadstack',       provider: 'lever', slug: 'squadstack',       sectors: ['bpo','sales'] },
  { name: 'Kapture CX',       provider: 'workable', slug: 'kapturecrm',    sectors: ['saas','bpo'] },
  { name: 'Ozonetel',         provider: 'workable', slug: 'ozonetel',      sectors: ['saas','bpo'] },
  { name: 'Verloop.io',       provider: 'workable', slug: 'verloop',       sectors: ['saas','bpo'] },

  /* ================= BATCH 2 — more genuine India ATS boards (sales / BPO / support / edtech / consumer) ================= */
  /* ----- Lever ----- */
  { name: 'PharmEasy',        provider: 'lever', slug: 'pharmeasy',        sectors: ['health','sales'] },
  { name: 'Purplle',          provider: 'lever', slug: 'purplle',          sectors: ['ecommerce','sales'] },
  { name: 'Livspace',         provider: 'lever', slug: 'livspace',         sectors: ['consumer','sales'] },
  { name: 'NoBroker',         provider: 'lever', slug: 'nobroker',         sectors: ['realestate','sales'] },
  { name: 'Rebel Foods',      provider: 'lever', slug: 'rebelfoods',       sectors: ['consumer','ops'] },
  { name: 'Porter',           provider: 'lever', slug: 'porter',           sectors: ['logistics','ops'] },
  { name: 'MPL',              provider: 'lever', slug: 'mpl',              sectors: ['gaming'] },
  { name: 'ShareChat',        provider: 'lever', slug: 'sharechat',        sectors: ['media'] },
  { name: 'Chargebee CX',     provider: 'lever', slug: 'chargebee',        sectors: ['saas'] },
  { name: 'InMobi',           provider: 'lever', slug: 'inmobi',           sectors: ['adtech','sales'] },
  { name: 'Glance',           provider: 'lever', slug: 'glance',           sectors: ['media'] },
  { name: 'Acko',             provider: 'lever', slug: 'acko',             sectors: ['insurtech','sales'] },
  { name: 'Navi',             provider: 'lever', slug: 'navi',             sectors: ['fintech','sales'] },
  { name: 'Cred',             provider: 'lever', slug: 'cred',             sectors: ['fintech'] },
  { name: 'M2P Fintech',      provider: 'lever', slug: 'm2pfintech',       sectors: ['fintech'] },
  { name: 'Zeta',             provider: 'lever', slug: 'zeta',             sectors: ['fintech'] },
  { name: 'Setu',             provider: 'lever', slug: 'setu',             sectors: ['fintech'] },
  { name: 'Signzy',           provider: 'lever', slug: 'signzy',           sectors: ['fintech'] },
  { name: 'Perfios',          provider: 'lever', slug: 'perfios',          sectors: ['fintech'] },
  { name: 'InsuranceDekho',   provider: 'lever', slug: 'insurancedekho',   sectors: ['insurtech','sales'] },
  { name: 'Turtlemint',       provider: 'lever', slug: 'turtlemint',       sectors: ['insurtech','sales'] },
  { name: 'BankBazaar',       provider: 'lever', slug: 'bankbazaar',       sectors: ['fintech','sales'] },
  { name: 'WhiteHat Jr',      provider: 'lever', slug: 'whitehatjr',       sectors: ['edtech','sales'] },
  { name: 'Toppr',            provider: 'lever', slug: 'toppr',            sectors: ['edtech','sales'] },
  { name: 'Skill-Lync',       provider: 'lever', slug: 'skilllync',        sectors: ['edtech','sales'] },
  { name: 'AlmaBetter',       provider: 'lever', slug: 'almabetter',       sectors: ['edtech','sales'] },
  { name: 'Masai School',     provider: 'lever', slug: 'masaischool',      sectors: ['edtech'] },
  { name: 'PrepLadder',       provider: 'lever', slug: 'prepladder',       sectors: ['edtech'] },
  { name: 'Adda247',          provider: 'lever', slug: 'adda247',          sectors: ['edtech','sales'] },
  { name: 'FrontRow',         provider: 'lever', slug: 'frontrow',         sectors: ['edtech'] },

  /* ----- Greenhouse ----- */
  { name: 'Swiggy',           provider: 'greenhouse', slug: 'swiggy',          sectors: ['consumer','ops'] },
  { name: 'Flipkart',         provider: 'greenhouse', slug: 'flipkart',        sectors: ['ecommerce','sales'] },
  { name: 'Myntra',           provider: 'greenhouse', slug: 'myntra',          sectors: ['ecommerce'] },
  { name: 'Ola',              provider: 'greenhouse', slug: 'olacabs',         sectors: ['consumer','ops'] },
  { name: 'Nykaa',            provider: 'greenhouse', slug: 'nykaa',           sectors: ['ecommerce','sales'] },
  { name: 'Paytm',            provider: 'greenhouse', slug: 'paytm',           sectors: ['fintech','sales'] },
  { name: 'Freshworks',       provider: 'greenhouse', slug: 'freshworks',      sectors: ['saas','sales'] },
  { name: 'Zoho',             provider: 'greenhouse', slug: 'zoho',            sectors: ['saas','sales'] },
  { name: 'Druva',            provider: 'greenhouse', slug: 'druva',           sectors: ['saas'] },
  { name: 'Icertis',          provider: 'greenhouse', slug: 'icertis',         sectors: ['saas'] },
  { name: 'Mad Street Den',   provider: 'greenhouse', slug: 'madstreetden',    sectors: ['ai'] },
  { name: 'Postman India',    provider: 'greenhouse', slug: 'postmanlabs',     sectors: ['saas'] },
  { name: 'Uber',             provider: 'greenhouse', slug: 'uber',            sectors: ['consumer','ops'] },
  { name: 'ThoughtSpot',      provider: 'greenhouse', slug: 'thoughtspot',     sectors: ['saas'] },
  { name: 'Chargebee GTM',    provider: 'greenhouse', slug: 'chargebee',       sectors: ['saas'] },
  { name: 'BrowserStack (G)', provider: 'greenhouse', slug: 'browserstack',    sectors: ['saas'] },

  /* ----- Ashby ----- */
  { name: 'Hasura (A)',       provider: 'ashby', slug: 'hasura',            sectors: ['saas'] },
  { name: 'Portkey',          provider: 'ashby', slug: 'portkey',           sectors: ['ai'] },
  { name: 'Sarvam AI',        provider: 'ashby', slug: 'sarvam',            sectors: ['ai'] },
  { name: 'CoRover',          provider: 'ashby', slug: 'corover',           sectors: ['ai','bpo'] },
  { name: 'Rocketlane',       provider: 'ashby', slug: 'rocketlane',        sectors: ['saas'] },
  { name: 'DevRev',           provider: 'ashby', slug: 'devrev',            sectors: ['saas'] },
  { name: 'SuperOps',         provider: 'ashby', slug: 'superops',          sectors: ['saas'] },
  { name: 'Nintee',           provider: 'ashby', slug: 'nintee',            sectors: ['health'] },

  /* ----- Workable (Indian startups) ----- */
  { name: 'Springboard',      provider: 'workable', slug: 'springboard',    sectors: ['edtech','sales'] },
  { name: 'Henry Harvin',     provider: 'workable', slug: 'henryharvin',    sectors: ['edtech','sales'] },
  { name: 'Board Infinity',   provider: 'workable', slug: 'boardinfinity',  sectors: ['edtech','sales'] },
  { name: 'Coding Ninjas',    provider: 'workable', slug: 'codingninjas',   sectors: ['edtech','sales'] },
  { name: 'Uolo',             provider: 'workable', slug: 'uolo',           sectors: ['edtech'] },
  { name: 'Filo',             provider: 'workable', slug: 'filo',           sectors: ['edtech'] },
  { name: 'SuperKalam',       provider: 'workable', slug: 'superkalam',     sectors: ['edtech'] },
  { name: 'Pariksha',         provider: 'workable', slug: 'pariksha',       sectors: ['edtech'] },
  { name: 'Wati',             provider: 'workable', slug: 'wati',           sectors: ['saas','bpo'] },
  { name: 'Gallabox',         provider: 'workable', slug: 'gallabox',       sectors: ['saas','bpo'] },
  { name: 'Interakt',         provider: 'workable', slug: 'interakt',       sectors: ['saas','bpo'] },
  { name: 'Fibotalk',         provider: 'workable', slug: 'fibotalk',       sectors: ['saas','bpo'] },
  { name: 'Locobuzz',         provider: 'workable', slug: 'locobuzz',       sectors: ['saas','bpo'] },

  /* ----- SmartRecruiters (India CX / retail / BFSI hiring) ----- */
  { name: 'Concentrix (SR)',  provider: 'smartrecruiters', slug: 'Concentrix',      sectors: ['bpo'] },
  { name: 'Tech Mahindra',    provider: 'smartrecruiters', slug: 'TechMahindra',    sectors: ['it-services','bpo'] },
  { name: 'Sutherland',       provider: 'smartrecruiters', slug: 'Sutherland',      sectors: ['bpo'] },
  { name: 'Sitel',            provider: 'smartrecruiters', slug: 'SitelGroup',      sectors: ['bpo'] },
  { name: 'HDFC Bank',        provider: 'smartrecruiters', slug: 'HDFCBank',        sectors: ['bfsi','sales'] },
  { name: 'DHL',              provider: 'smartrecruiters', slug: 'DHL',             sectors: ['logistics'] },
  { name: 'Coca-Cola',        provider: 'smartrecruiters', slug: 'CocaColaHBC',     sectors: ['consumer'] },

  /* ----- Recruitee ----- */
  { name: 'FreJun',           provider: 'recruitee', slug: 'frejun',        sectors: ['saas','bpo'] },
  { name: 'Zenskar',          provider: 'recruitee', slug: 'zenskar',       sectors: ['saas'] },
  { name: 'Plivo',            provider: 'recruitee', slug: 'plivo',         sectors: ['saas','bpo'] },

  /* ================= BATCH 3 — high-yield global SaaS (India offices) + big Indian consumer/fintech ================= */
  /* ----- Greenhouse: global SaaS/data/infra with large India dev+GTM centers (these return many India jobs) ----- */
  { name: 'Elastic',          provider: 'greenhouse', slug: 'elastic',         sectors: ['saas'] },
  { name: 'HashiCorp',        provider: 'greenhouse', slug: 'hashicorp',       sectors: ['saas'] },
  { name: 'New Relic',        provider: 'greenhouse', slug: 'newrelic',        sectors: ['saas'] },
  { name: 'PagerDuty',        provider: 'greenhouse', slug: 'pagerduty',       sectors: ['saas'] },
  { name: 'Sumo Logic',       provider: 'greenhouse', slug: 'sumologic',       sectors: ['saas'] },
  { name: 'Braze',            provider: 'greenhouse', slug: 'braze',           sectors: ['saas'] },
  { name: 'Mixpanel',         provider: 'greenhouse', slug: 'mixpanel',        sectors: ['saas'] },
  { name: 'Redis',            provider: 'greenhouse', slug: 'redislabs',       sectors: ['saas'] },
  { name: 'Grafana Labs',     provider: 'greenhouse', slug: 'grafanalabs',     sectors: ['saas'] },
  { name: 'Fivetran',         provider: 'greenhouse', slug: 'fivetran',        sectors: ['saas'] },
  { name: 'Starburst',        provider: 'greenhouse', slug: 'starburstdata',   sectors: ['saas'] },
  { name: 'Harness',          provider: 'greenhouse', slug: 'harness',         sectors: ['saas'] },
  { name: 'Cohesity',         provider: 'greenhouse', slug: 'cohesity',        sectors: ['saas'] },
  { name: '6sense',           provider: 'greenhouse', slug: 'sixsense',        sectors: ['saas','sales'] },
  { name: 'Clari',            provider: 'greenhouse', slug: 'clari',           sectors: ['saas','sales'] },
  { name: 'Outreach',         provider: 'greenhouse', slug: 'outreach',        sectors: ['saas','sales'] },
  { name: 'Salesloft',        provider: 'greenhouse', slug: 'salesloft',       sectors: ['saas','sales'] },
  { name: 'WebEngage',        provider: 'greenhouse', slug: 'webengage',       sectors: ['saas','sales'] },
  { name: 'Uniphore',         provider: 'greenhouse', slug: 'uniphore',        sectors: ['saas','bpo'] },
  { name: 'Wayfair',          provider: 'greenhouse', slug: 'wayfair',         sectors: ['ecommerce'] },
  { name: 'Reddit',           provider: 'greenhouse', slug: 'reddit',          sectors: ['media'] },
  { name: 'Pinterest',        provider: 'greenhouse', slug: 'pinterest',       sectors: ['media'] },
  { name: 'Roblox',           provider: 'greenhouse', slug: 'roblox',          sectors: ['gaming'] },
  { name: 'Unity',            provider: 'greenhouse', slug: 'unity3d',         sectors: ['gaming'] },
  { name: 'Plaid',            provider: 'greenhouse', slug: 'plaid',           sectors: ['fintech'] },
  { name: 'Block',            provider: 'greenhouse', slug: 'block',           sectors: ['fintech'] },
  { name: 'Yelp',             provider: 'greenhouse', slug: 'yelp',            sectors: ['consumer'] },

  /* ----- Lever: more India-hiring SaaS/consumer ----- */
  { name: 'CoinDCX',          provider: 'lever', slug: 'coindcx',          sectors: ['fintech','sales'] },
  { name: 'CoinSwitch',       provider: 'lever', slug: 'coinswitch',       sectors: ['fintech','sales'] },
  { name: 'Lenskart',         provider: 'lever', slug: 'lenskart',         sectors: ['consumer','sales'] },
  { name: 'boAt',             provider: 'lever', slug: 'boat',             sectors: ['consumer'] },
  { name: 'Mamaearth',        provider: 'lever', slug: 'honasa',           sectors: ['consumer','sales'] },
  { name: 'Zetwerk',          provider: 'lever', slug: 'zetwerk',          sectors: ['manufacturing','sales'] },
  { name: 'Moglix',           provider: 'lever', slug: 'moglix',           sectors: ['ecommerce','sales'] },
  { name: 'OfBusiness',       provider: 'lever', slug: 'ofbusiness',       sectors: ['fintech','sales'] },
  { name: 'Urban Company',    provider: 'lever', slug: 'urbancompany',     sectors: ['consumer','ops'] },
  { name: 'Delhivery',        provider: 'lever', slug: 'delhivery',        sectors: ['logistics','ops'] },
  { name: 'CarDekho',         provider: 'lever', slug: 'cardekho',         sectors: ['auto','sales'] },
  { name: 'Rapido',           provider: 'lever', slug: 'rapido',           sectors: ['consumer','ops'] },
  { name: 'Practo',           provider: 'lever', slug: 'practo',           sectors: ['health','sales'] },
  { name: 'Tata 1mg',         provider: 'lever', slug: 'tata1mg',          sectors: ['health','sales'] },
  { name: 'HealthifyMe',      provider: 'lever', slug: 'healthifyme',      sectors: ['health','sales'] },
  { name: 'Licious',          provider: 'lever', slug: 'licious',          sectors: ['consumer','ops'] },
  { name: 'Country Delight',  provider: 'lever', slug: 'countrydelight',   sectors: ['consumer','sales'] },
  { name: 'Ather Energy',     provider: 'lever', slug: 'atherenergy',      sectors: ['auto','sales'] },
  { name: 'Yubi',             provider: 'lever', slug: 'go-yubi',          sectors: ['fintech','sales'] },
  { name: 'ClearTax',         provider: 'lever', slug: 'cleartax',         sectors: ['fintech','sales'] },
  { name: 'MediBuddy',        provider: 'lever', slug: 'medibuddy',        sectors: ['health','sales'] },
  { name: 'Pristyn Care',     provider: 'lever', slug: 'pristyncare',      sectors: ['health','sales'] },
  { name: 'Bewakoof',         provider: 'lever', slug: 'bewakoof',         sectors: ['ecommerce','sales'] },
  { name: 'WickedRide/Bounce',provider: 'lever', slug: 'bounce',           sectors: ['consumer','ops'] },

  /* ----- Ashby: India-founded / India-office startups ----- */
  { name: 'CleverTap (A)',    provider: 'ashby', slug: 'clevertap',        sectors: ['saas','sales'] },
  { name: 'Postman (A)',      provider: 'ashby', slug: 'postman',          sectors: ['saas'] },
  { name: 'Spinny (A)',       provider: 'ashby', slug: 'spinny',           sectors: ['auto','sales'] },
  { name: 'Jai Kisan',        provider: 'ashby', slug: 'jaikisan',         sectors: ['fintech','sales'] },
  { name: 'Bimaplan',         provider: 'ashby', slug: 'bimaplan',         sectors: ['insurtech','sales'] },

  /* ----- Workable: more Indian SMB / edtech / CX ----- */
  { name: 'Skillovilla',      provider: 'workable', slug: 'skillovilla',   sectors: ['edtech','sales'] },
  { name: 'AntWalk',          provider: 'workable', slug: 'antwalk',       sectors: ['edtech','sales'] },
  { name: 'PlanetSpark',      provider: 'workable', slug: 'planetspark',   sectors: ['edtech','sales'] },
  { name: 'Camp K12',         provider: 'workable', slug: 'campk12',       sectors: ['edtech','sales'] },
  { name: 'DoubtnutApp',      provider: 'workable', slug: 'doubtnut',      sectors: ['edtech'] },
  { name: 'Exlyapp',          provider: 'workable', slug: 'exly',          sectors: ['saas','sales'] },
  { name: 'Nurture Farm',     provider: 'workable', slug: 'nurturefarm',   sectors: ['agri','sales'] },

  /* ----- SmartRecruiters: large CX / retail / BFSI India hiring ----- */
  { name: 'Teleperformance',  provider: 'smartrecruiters', slug: 'Teleperformance', sectors: ['bpo'] },
  { name: 'iEnergizer',       provider: 'smartrecruiters', slug: 'iEnergizer',      sectors: ['bpo'] },
  { name: 'Genpact',          provider: 'smartrecruiters', slug: 'Genpact',         sectors: ['bpo'] },
  { name: 'WNS',              provider: 'smartrecruiters', slug: 'WNS',             sectors: ['bpo'] },
  { name: 'Reliance Retail',  provider: 'smartrecruiters', slug: 'RelianceRetail',  sectors: ['retail','sales'] },
  { name: 'Aditya Birla',     provider: 'smartrecruiters', slug: 'AdityaBirlaGroup',sectors: ['retail','sales'] }
];
